namespace Website.Models.Database.Enums
{
    public enum GameplayEventType
    {
        Unspecified,
        CharacterDied,
        ItemCollected,
        DownToTheNextFloor,
        Bossfight,
        Pill,
        TarotCard,
        Rune,
        Trinket,
        Curse,
        OtherConsumable,
        TransformationComplete,
        TransformationProgress,
        LastFloor,
        AbsorbedItem,
        CharacterReroll,
        WonTheRun,
        LostTheRun,
        ItemTouched,
        StartingTrinket,
        Clicker,
        RerollTransform,
        Respawn,
        TaintedIsaacReplacedItem
    }
}
