import { ExistsIn } from "../../Enums/exists-in";
import { convertExistsInToString, convertGameModeToString, convertResourceTypeToString, convertTagToString } from "../../Enums/enum-to-string-converters";
import { Option } from '../General/option';
import { GameMode } from "../../Enums/game-mode";
import { ResourceType } from "../../Enums/resource-type";
import { Tag } from "../../Enums/tags";

const gameModeOptionList = (selectedOption?: GameMode) => {
    return [
        new Option(GameMode.AllModes.toString(10), convertGameModeToString(GameMode.AllModes), selectedOption === GameMode.AllModes ? true : false),
        new Option(GameMode.CommunityChallenge.toString(10), convertGameModeToString(GameMode.CommunityChallenge), selectedOption === GameMode.CommunityChallenge ? true : false),
        new Option(GameMode.Greed.toString(10), convertGameModeToString(GameMode.Greed), selectedOption === GameMode.Greed ? true : false),
        new Option(GameMode.Greedier.toString(10), convertGameModeToString(GameMode.Greedier), selectedOption === GameMode.Greedier ? true : false),
        new Option(GameMode.Hard.toString(10), convertGameModeToString(GameMode.Hard), selectedOption === GameMode.Hard ? true : false),
        new Option(GameMode.Normal.toString(10), convertGameModeToString(GameMode.Normal), selectedOption === GameMode.Normal ? true : false),
        new Option(GameMode.HardAndNormal.toString(10), convertGameModeToString(GameMode.HardAndNormal), selectedOption === GameMode.HardAndNormal ? true : false),
        new Option(GameMode.SpecialChallenge.toString(10), convertGameModeToString(GameMode.SpecialChallenge), selectedOption === GameMode.SpecialChallenge ? true : false),
        new Option(GameMode.SpecialSeed.toString(10), convertGameModeToString(GameMode.SpecialSeed), selectedOption === GameMode.SpecialSeed ? true : false),
        new Option(GameMode.Unspecified.toString(10), convertGameModeToString(GameMode.Unspecified), selectedOption === GameMode.Unspecified ? true : false),
    ];
}

const existsInOptionlist = (selected?: ExistsIn) => {
    return [
        new Option(ExistsIn.VanillaOnwards.toString(10), convertExistsInToString(ExistsIn.VanillaOnwards), selected === ExistsIn.VanillaOnwards ? true : false),
        new Option(ExistsIn.VanillaOnly.toString(10), convertExistsInToString(ExistsIn.VanillaOnly), selected === ExistsIn.VanillaOnly ? true : false),
        new Option(ExistsIn.WrathOfTheLambOnwards.toString(10), convertExistsInToString(ExistsIn.WrathOfTheLambOnwards), selected === ExistsIn.WrathOfTheLambOnwards ? true : false),
        new Option(ExistsIn.WrathOfTheLambOnly.toString(10), convertExistsInToString(ExistsIn.WrathOfTheLambOnly), selected === ExistsIn.WrathOfTheLambOnly ? true : false),
        new Option(ExistsIn.CommunityRemixOnwards.toString(10), convertExistsInToString(ExistsIn.CommunityRemixOnwards), selected === ExistsIn.CommunityRemixOnwards ? true : false),
        new Option(ExistsIn.CommunityRemixOnly.toString(10), convertExistsInToString(ExistsIn.CommunityRemixOnly), selected === ExistsIn.CommunityRemixOnly ? true : false),
        new Option(ExistsIn.RebirthOnwards.toString(10), convertExistsInToString(ExistsIn.RebirthOnwards), selected === ExistsIn.RebirthOnwards ? true : false),
        new Option(ExistsIn.RebirthOnly.toString(10), convertExistsInToString(ExistsIn.RebirthOnly), selected === ExistsIn.RebirthOnly ? true : false),
        new Option(ExistsIn.AfterbirthOnwards.toString(10), convertExistsInToString(ExistsIn.AfterbirthOnwards), selected === ExistsIn.AfterbirthOnwards ? true : false),
        new Option(ExistsIn.AfterbirthOnly.toString(10), convertExistsInToString(ExistsIn.AntibirthAndRepentanceOnwards), selected === ExistsIn.AntibirthAndRepentanceOnwards ? true : false),
        new Option(ExistsIn.AntibirthOnly.toString(10), convertExistsInToString(ExistsIn.AntibirthOnly), selected === ExistsIn.AntibirthOnly ? true : false),
        new Option(ExistsIn.AnitbirthOnwards.toString(10), convertExistsInToString(ExistsIn.AnitbirthOnwards), selected === ExistsIn.AnitbirthOnwards ? true : false),
        new Option(ExistsIn.AntibirthAndRepentanceOnwards.toString(10), convertExistsInToString(ExistsIn.AntibirthAndRepentanceOnwards), selected === ExistsIn.AntibirthAndRepentanceOnwards ? true : false),
        new Option(ExistsIn.AfterbirthPlusOnwards.toString(10), convertExistsInToString(ExistsIn.AfterbirthPlusOnwards), selected === ExistsIn.AfterbirthPlusOnwards ? true : false),
        new Option(ExistsIn.AfterbirthPlusOnly.toString(10), convertExistsInToString(ExistsIn.AfterbirthPlusOnly), selected === ExistsIn.AfterbirthPlusOnly ? true : false),
        new Option(ExistsIn.BoosterPack1Onwards.toString(10), convertExistsInToString(ExistsIn.BoosterPack1Onwards), selected === ExistsIn.BoosterPack1Onwards ? true : false),
        new Option(ExistsIn.BoosterPack1Only.toString(10), convertExistsInToString(ExistsIn.BoosterPack1Only), selected === ExistsIn.BoosterPack1Only ? true : false),
        new Option(ExistsIn.BoosterPack2Onwards.toString(10), convertExistsInToString(ExistsIn.BoosterPack2Onwards), selected === ExistsIn.BoosterPack2Onwards ? true : false),
        new Option(ExistsIn.BoosterPack2Only.toString(10), convertExistsInToString(ExistsIn.BoosterPack2Only), selected === ExistsIn.BoosterPack2Only ? true : false),
        new Option(ExistsIn.BoosterPack3Onwards.toString(10), convertExistsInToString(ExistsIn.BoosterPack3Onwards), selected === ExistsIn.BoosterPack3Onwards ? true : false),
        new Option(ExistsIn.BoosterPack3Only.toString(10), convertExistsInToString(ExistsIn.BoosterPack3Only), selected === ExistsIn.BoosterPack3Only ? true : false),
        new Option(ExistsIn.BoosterPack4Onwards.toString(10), convertExistsInToString(ExistsIn.BoosterPack4Onwards), selected === ExistsIn.BoosterPack4Onwards ? true : false),
        new Option(ExistsIn.BoosterPack4Only.toString(10), convertExistsInToString(ExistsIn.BoosterPack4Only), selected === ExistsIn.BoosterPack4Only ? true : false),
        new Option(ExistsIn.BoosterPack5Onwards.toString(10), convertExistsInToString(ExistsIn.BoosterPack5Onwards), selected === ExistsIn.BoosterPack5Onwards ? true : false),
        new Option(ExistsIn.BoosterPack5Only.toString(10), convertExistsInToString(ExistsIn.BoosterPack5Only), selected === ExistsIn.BoosterPack5Only ? true : false),
        new Option(ExistsIn.RepentanceOnwards.toString(10), convertExistsInToString(ExistsIn.RepentanceOnwards), selected === ExistsIn.RepentanceOnwards ? true : false),
        new Option(ExistsIn.RepentanceOnly.toString(10), convertExistsInToString(ExistsIn.RepentanceOnly), selected === ExistsIn.RepentanceOnly ? true : false),
        new Option(ExistsIn.EveryVersion.toString(10), convertExistsInToString(ExistsIn.EveryVersion), selected === ExistsIn.EveryVersion ? true : false),
        new Option(ExistsIn.Nowhere.toString(10), convertExistsInToString(ExistsIn.Nowhere), selected === ExistsIn.Nowhere ? true : false),
        new Option(ExistsIn.Unspecified.toString(10), convertExistsInToString(ExistsIn.Unspecified), selected === ExistsIn.Unspecified ? true : false),
        new Option(ExistsIn.CommunityRemixAndAntibirth.toString(10), convertExistsInToString(ExistsIn.CommunityRemixAndAntibirth), selected === ExistsIn.CommunityRemixAndAntibirth ? true : false),
        new Option(ExistsIn.CommunityRemixAndAntibirthAndRepentanceOnwards.toString(10), convertExistsInToString(ExistsIn.CommunityRemixAndAntibirthAndRepentanceOnwards), selected === ExistsIn.CommunityRemixAndAntibirthAndRepentanceOnwards ? true : false),
        new Option(ExistsIn.CommunityRemixAndAntibirthAndAfterbirthOnwards.toString(10), convertExistsInToString(ExistsIn.CommunityRemixAndAntibirthAndAfterbirthOnwards), selected === ExistsIn.CommunityRemixAndAntibirthAndAfterbirthOnwards ? true : false),
        new Option(ExistsIn.VanillaAndWrathOfTheLambExclusive.toString(10), convertExistsInToString(ExistsIn.VanillaAndWrathOfTheLambExclusive), selected === ExistsIn.VanillaAndWrathOfTheLambExclusive ? true : false),
        new Option(ExistsIn.CommunityRemixAndRebirthOnwards.toString(10), convertExistsInToString(ExistsIn.CommunityRemixAndRebirthOnwards), selected === ExistsIn.CommunityRemixAndRebirthOnwards ? true : false),
    ];
}

const resourceTypeOptionList = (resourceType?: ResourceType) => {
    return [
        new Option(ResourceType.Boss.toString(10), convertResourceTypeToString(ResourceType.Boss), resourceType === ResourceType.Boss ? true : false),
        new Option(ResourceType.Character.toString(10), convertResourceTypeToString(ResourceType.Character), resourceType === ResourceType.Character ? true : false),
        new Option(ResourceType.CharacterReroll.toString(10), convertResourceTypeToString(ResourceType.CharacterReroll), resourceType === ResourceType.CharacterReroll ? true : false),
        new Option(ResourceType.Curse.toString(10), convertResourceTypeToString(ResourceType.Curse), resourceType === ResourceType.Curse ? true : false),
        new Option(ResourceType.Enemy.toString(10), convertResourceTypeToString(ResourceType.Enemy), resourceType === ResourceType.Enemy ? true : false),
        new Option(ResourceType.Floor.toString(10), convertResourceTypeToString(ResourceType.Floor), resourceType === ResourceType.Floor ? true : false),
        new Option(ResourceType.Item.toString(10), convertResourceTypeToString(ResourceType.Item), resourceType === ResourceType.Item ? true : false),
        new Option(ResourceType.ItemSource.toString(10), convertResourceTypeToString(ResourceType.ItemSource), resourceType === ResourceType.ItemSource ? true : false),
        new Option(ResourceType.OtherConsumable.toString(10), convertResourceTypeToString(ResourceType.OtherConsumable), resourceType === ResourceType.OtherConsumable ? true : false),
        new Option(ResourceType.OtherEvent.toString(10), convertResourceTypeToString(ResourceType.OtherEvent), resourceType === ResourceType.OtherEvent ? true : false),
        new Option(ResourceType.Pill.toString(10), convertResourceTypeToString(ResourceType.Pill), resourceType === ResourceType.Pill ? true : false),
        new Option(ResourceType.Rune.toString(10), convertResourceTypeToString(ResourceType.Rune), resourceType === ResourceType.Rune ? true : false),
        new Option(ResourceType.TarotCard.toString(10), convertResourceTypeToString(ResourceType.TarotCard), resourceType === ResourceType.TarotCard ? true : false),
        new Option(ResourceType.Transformation.toString(10), convertResourceTypeToString(ResourceType.Transformation), resourceType === ResourceType.Transformation ? true : false),
        new Option(ResourceType.Trinket.toString(10), convertResourceTypeToString(ResourceType.Trinket), resourceType === ResourceType.Trinket ? true : false),
        new Option(ResourceType.Unspecified.toString(10), convertResourceTypeToString(ResourceType.Unspecified), resourceType === ResourceType.Unspecified ? true : false)
    ];
}

const tagsOptionList = (selectedTags?: Array<Tag>) => {
    return [
        new Option('', 'Choose...', selectedTags && selectedTags.length === 0 ? true : false),
        new Option(Tag.Unspecified.toString(10), convertTagToString(Tag.Unspecified), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Unspecified) !== -1),
        new Option(Tag.ChangesDropBehavior.toString(10), convertTagToString(Tag.ChangesDropBehavior), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ChangesDropBehavior) !== -1),
        new Option(Tag.ChangesItemBehavior.toString(10), convertTagToString(Tag.ChangesItemBehavior), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ChangesItemBehavior) !== -1),
        new Option(Tag.ModifiesFamiliars.toString(10), convertTagToString(Tag.ModifiesFamiliars), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ModifiesFamiliars) !== -1),
        new Option(Tag.CanSpawnFlies.toString(10), convertTagToString(Tag.CanSpawnFlies), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.CanSpawnFlies) !== -1),
        new Option(Tag.CanSpawnSpiders.toString(10), convertTagToString(Tag.CanSpawnSpiders), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.CanSpawnSpiders) !== -1),
        new Option(Tag.DamageReduction.toString(10), convertTagToString(Tag.DamageReduction), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DamageReduction) !== -1),
        new Option(Tag.Invincibility.toString(10), convertTagToString(Tag.Invincibility), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Invincibility) !== -1),
        new Option(Tag.ChangesBombBehavior.toString(10), convertTagToString(Tag.ChangesBombBehavior), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ChangesBombBehavior) !== -1),
        new Option(Tag.RoomDamage.toString(10), convertTagToString(Tag.RoomDamage), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.RoomDamage) !== -1),
        new Option(Tag.HpRegeneration.toString(10), convertTagToString(Tag.HpRegeneration), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.HpRegeneration) !== -1),
        new Option(Tag.MapReveal.toString(10), convertTagToString(Tag.MapReveal), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.MapReveal) !== -1),
        new Option(Tag.TimeManipulation.toString(10), convertTagToString(Tag.TimeManipulation), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.TimeManipulation) !== -1),
        new Option(Tag.SplashDamage.toString(10), convertTagToString(Tag.SplashDamage), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.SplashDamage) !== -1),
        new Option(Tag.Recharge.toString(10), convertTagToString(Tag.Recharge), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Recharge) !== -1),
        new Option(Tag.BeamsFromHeaven.toString(10), convertTagToString(Tag.BeamsFromHeaven), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.BeamsFromHeaven) !== -1),
        new Option(Tag.TriggersOnGettingHit.toString(10), convertTagToString(Tag.TriggersOnGettingHit), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.TriggersOnGettingHit) !== -1),
        new Option(Tag.GeneratesItem.toString(10), convertTagToString(Tag.GeneratesItem), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.GeneratesItem) !== -1),
        new Option(Tag.DamagesSelfOnUse.toString(10), convertTagToString(Tag.DamagesSelfOnUse), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DamagesSelfOnUse) !== -1),
        new Option(Tag.SizeUp.toString(10), convertTagToString(Tag.SizeUp), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.SizeUp) !== -1),
        new Option(Tag.SizeDown.toString(10), convertTagToString(Tag.SizeDown), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.SizeDown) !== -1),
        new Option(Tag.Teleport.toString(10), convertTagToString(Tag.Teleport), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Teleport) !== -1),
        new Option(Tag.DropsKeys.toString(10), convertTagToString(Tag.DropsKeys), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DropsKeys) !== -1),
        new Option(Tag.DropsBombs.toString(10), convertTagToString(Tag.DropsBombs), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DropsBombs) !== -1),
        new Option(Tag.DropsBatteries.toString(10), convertTagToString(Tag.DropsBatteries), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DropsBatteries) !== -1),
        new Option(Tag.DropsRedHearts.toString(10), convertTagToString(Tag.DropsRedHearts), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DropsRedHearts) !== -1),
        new Option(Tag.DropsSpiritHearts.toString(10), convertTagToString(Tag.DropsSpiritHearts), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DropsSpiritHearts) !== -1),
        new Option(Tag.DropsRottenHearts.toString(10), convertTagToString(Tag.DropsRottenHearts), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DropsRottenHearts) !== -1),
        new Option(Tag.DropsEternalHearts.toString(10), convertTagToString(Tag.DropsEternalHearts), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DropsEternalHearts) !== -1),
        new Option(Tag.DropsBoneHearts.toString(10), convertTagToString(Tag.DropsBoneHearts), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DropsBoneHearts) !== -1),
        new Option(Tag.DropsBlackHearts.toString(10), convertTagToString(Tag.DropsBlackHearts), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DropsBlackHearts) !== -1),
        new Option(Tag.DropsImmortalHearts.toString(10), convertTagToString(Tag.DropsImmortalHearts), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DropsImmortalHearts) !== -1),
        new Option(Tag.DropsTarotCards.toString(10), convertTagToString(Tag.DropsTarotCards), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DropsTarotCards) !== -1),
        new Option(Tag.DropsTrinkets.toString(10), convertTagToString(Tag.DropsTrinkets), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DropsTrinkets) !== -1),
        new Option(Tag.DropsPills.toString(10), convertTagToString(Tag.DropsPills), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DropsPills) !== -1),
        new Option(Tag.DropsChests.toString(10), convertTagToString(Tag.DropsChests), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DropsChests) !== -1),
        new Option(Tag.DropsSacks.toString(10), convertTagToString(Tag.DropsSacks), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DropsSacks) !== -1),
        new Option(Tag.DropsRunes.toString(10), convertTagToString(Tag.DropsRunes), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DropsRunes) !== -1),
        new Option(Tag.DropsPennies.toString(10), convertTagToString(Tag.DropsPennies), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DropsPennies) !== -1),
        new Option(Tag.AddsKeys.toString(10), convertTagToString(Tag.AddsKeys), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AddsKeys) !== -1),
        new Option(Tag.AddsBombs.toString(10), convertTagToString(Tag.AddsBombs), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AddsBombs) !== -1),
        new Option(Tag.AddsRedHearts.toString(10), convertTagToString(Tag.AddsRedHearts), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AddsRedHearts) !== -1),
        new Option(Tag.AddsSpiritHearts.toString(10), convertTagToString(Tag.AddsSpiritHearts), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AddsSpiritHearts) !== -1),
        new Option(Tag.AddsRottenHearts.toString(10), convertTagToString(Tag.AddsRottenHearts), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AddsRottenHearts) !== -1),
        new Option(Tag.AddsEternalHearts.toString(10), convertTagToString(Tag.AddsEternalHearts), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AddsEternalHearts) !== -1),
        new Option(Tag.AddsBoneHearts.toString(10), convertTagToString(Tag.AddsBoneHearts), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AddsBoneHearts) !== -1),
        new Option(Tag.AddsBlackHearts.toString(10), convertTagToString(Tag.AddsBlackHearts), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AddsBlackHearts) !== -1),
        new Option(Tag.AddsImmortalHearts.toString(10), convertTagToString(Tag.AddsImmortalHearts), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AddsImmortalHearts) !== -1),
        new Option(Tag.AddsTarotCards.toString(10), convertTagToString(Tag.AddsTarotCards), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AddsTarotCards) !== -1),
        new Option(Tag.AddsTrinkets.toString(10), convertTagToString(Tag.AddsTrinkets), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AddsTrinkets) !== -1),
        new Option(Tag.AddsPills.toString(10), convertTagToString(Tag.AddsPills), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AddsPills) !== -1),
        new Option(Tag.AddsRunes.toString(10), convertTagToString(Tag.AddsRunes), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AddsRunes) !== -1),
        new Option(Tag.AddsPennies.toString(10), convertTagToString(Tag.AddsPennies), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AddsPennies) !== -1),
        new Option(Tag.Charm.toString(10), convertTagToString(Tag.Charm), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Charm) !== -1),
        new Option(Tag.Beam.toString(10), convertTagToString(Tag.Beam), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Beam) !== -1),
        new Option(Tag.Poison.toString(10), convertTagToString(Tag.Poison), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Poison) !== -1),
        new Option(Tag.Slow.toString(10), convertTagToString(Tag.Slow), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Slow) !== -1),
        new Option(Tag.Fear.toString(10), convertTagToString(Tag.Fear), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Fear) !== -1),
        new Option(Tag.Explosion.toString(10), convertTagToString(Tag.Explosion), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Explosion) !== -1),
        new Option(Tag.Freeze.toString(10), convertTagToString(Tag.Freeze), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Freeze) !== -1),
        new Option(Tag.Burn.toString(10), convertTagToString(Tag.Burn), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Burn) !== -1),
        new Option(Tag.Confuse.toString(10), convertTagToString(Tag.Confuse), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Confuse) !== -1),
        new Option(Tag.Spectral.toString(10), convertTagToString(Tag.Spectral), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Spectral) !== -1),
        new Option(Tag.Homing.toString(10), convertTagToString(Tag.Homing), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Homing) !== -1),
        new Option(Tag.Piercing.toString(10), convertTagToString(Tag.Piercing), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Piercing) !== -1),
        new Option(Tag.Shrink.toString(10), convertTagToString(Tag.Shrink), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Shrink) !== -1),
        new Option(Tag.Bleed.toString(10), convertTagToString(Tag.Bleed), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Bleed) !== -1),
        new Option(Tag.ExtraTears.toString(10), convertTagToString(Tag.ExtraTears), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ExtraTears) !== -1),
        new Option(Tag.VisualTearChange.toString(10), convertTagToString(Tag.VisualTearChange), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.VisualTearChange) !== -1),
        new Option(Tag.ChangesDealBehavior.toString(10), convertTagToString(Tag.ChangesDealBehavior), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ChangesDealBehavior) !== -1),
        new Option(Tag.ChangesTearBehavior.toString(10), convertTagToString(Tag.ChangesTearBehavior), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ChangesTearBehavior) !== -1),
        new Option(Tag.ChangesEnemyBehavior.toString(10), convertTagToString(Tag.ChangesEnemyBehavior), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ChangesEnemyBehavior) !== -1),
        new Option(Tag.Flight.toString(10), convertTagToString(Tag.Flight), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Flight) !== -1),
        new Option(Tag.ExtraLives.toString(10), convertTagToString(Tag.ExtraLives), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ExtraLives) !== -1),
        new Option(Tag.ExplosionImmunity.toString(10), convertTagToString(Tag.ExplosionImmunity), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ExplosionImmunity) !== -1),
        new Option(Tag.ChargeBar.toString(10), convertTagToString(Tag.ChargeBar), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ChargeBar) !== -1),
        new Option(Tag.Creep.toString(10), convertTagToString(Tag.Creep), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Creep) !== -1),
        new Option(Tag.WalkOverGaps.toString(10), convertTagToString(Tag.WalkOverGaps), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.WalkOverGaps) !== -1),
        new Option(Tag.MoreTrinketSpace.toString(10), convertTagToString(Tag.MoreTrinketSpace), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.MoreTrinketSpace) !== -1),
        new Option(Tag.MoreConsumableSpace.toString(10), convertTagToString(Tag.MoreConsumableSpace), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.MoreConsumableSpace) !== -1),
        new Option(Tag.CurseUp.toString(10), convertTagToString(Tag.CurseUp), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.CurseUp) !== -1),
        new Option(Tag.EvilUp.toString(10), convertTagToString(Tag.EvilUp), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.EvilUp) !== -1),
        new Option(Tag.EvilDown.toString(10), convertTagToString(Tag.EvilDown), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.EvilDown) !== -1),
        new Option(Tag.FaithUp.toString(10), convertTagToString(Tag.FaithUp), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.FaithUp) !== -1),
        new Option(Tag.FaithDown.toString(10), convertTagToString(Tag.FaithDown), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.FaithDown) !== -1),
        new Option(Tag.KnockbackUp.toString(10), convertTagToString(Tag.KnockbackUp), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.KnockbackUp) !== -1),
        new Option(Tag.KnockbackDown.toString(10), convertTagToString(Tag.KnockbackDown), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.KnockbackDown) !== -1),
        new Option(Tag.TearHeightUp.toString(10), convertTagToString(Tag.TearHeightUp), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.TearHeightUp) !== -1),
        new Option(Tag.TearHeightDown.toString(10), convertTagToString(Tag.TearHeightDown), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.TearHeightDown) !== -1),
        new Option(Tag.SinUp.toString(10), convertTagToString(Tag.SinUp), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.SinUp) !== -1),
        new Option(Tag.TearSizeUp.toString(10), convertTagToString(Tag.TearSizeUp), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.TearSizeUp) !== -1),
        new Option(Tag.TearSizeDown.toString(10), convertTagToString(Tag.TearSizeDown), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.TearSizeDown) !== -1),
        new Option(Tag.DamageUpTemporary.toString(10), convertTagToString(Tag.DamageUpTemporary), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DamageUpTemporary) !== -1),
        new Option(Tag.SpeedUpTemporary.toString(10), convertTagToString(Tag.SpeedUpTemporary), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.SpeedUpTemporary) !== -1),
        new Option(Tag.ShotSpeedUpTemporary.toString(10), convertTagToString(Tag.ShotSpeedUpTemporary), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ShotSpeedUpTemporary) !== -1),
        new Option(Tag.TearsUpTemporary.toString(10), convertTagToString(Tag.TearsUpTemporary), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.TearsUpTemporary) !== -1),
        new Option(Tag.HealthUpTemporary.toString(10), convertTagToString(Tag.HealthUpTemporary), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.HealthUpTemporary) !== -1),
        new Option(Tag.RangeUpTemporary.toString(10), convertTagToString(Tag.RangeUpTemporary), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.RangeUpTemporary) !== -1),
        new Option(Tag.LuckUpTemporary.toString(10), convertTagToString(Tag.LuckUpTemporary), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.LuckUpTemporary) !== -1),
        new Option(Tag.DamageUp.toString(10), convertTagToString(Tag.DamageUp), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DamageUp) !== -1),
        new Option(Tag.SpeedUp.toString(10), convertTagToString(Tag.SpeedUp), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.SpeedUp) !== -1),
        new Option(Tag.ShotSpeedUp.toString(10), convertTagToString(Tag.ShotSpeedUp), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ShotSpeedUp) !== -1),
        new Option(Tag.TearsUp.toString(10), convertTagToString(Tag.TearsUp), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.TearsUp) !== -1),
        new Option(Tag.HealthUp.toString(10), convertTagToString(Tag.HealthUp), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.HealthUp) !== -1),
        new Option(Tag.RangeUp.toString(10), convertTagToString(Tag.RangeUp), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.RangeUp) !== -1),
        new Option(Tag.LuckUp.toString(10), convertTagToString(Tag.LuckUp), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.LuckUp) !== -1),
        new Option(Tag.DamageDownTemporary.toString(10), convertTagToString(Tag.DamageDownTemporary), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DamageDownTemporary) !== -1),
        new Option(Tag.SpeedDownTemporary.toString(10), convertTagToString(Tag.SpeedDownTemporary), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.SpeedDownTemporary) !== -1),
        new Option(Tag.ShotSpeedDownTemporary.toString(10), convertTagToString(Tag.ShotSpeedDownTemporary), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ShotSpeedDownTemporary) !== -1),
        new Option(Tag.TearsDownTemporary.toString(10), convertTagToString(Tag.TearsDownTemporary), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.TearsDownTemporary) !== -1),
        new Option(Tag.HealthDownTemporary.toString(10), convertTagToString(Tag.HealthDownTemporary), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.HealthDownTemporary) !== -1),
        new Option(Tag.RangeDownTemporary.toString(10), convertTagToString(Tag.RangeDownTemporary), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.RangeDownTemporary) !== -1),
        new Option(Tag.LuckDownTemporary.toString(10), convertTagToString(Tag.LuckDownTemporary), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.LuckDownTemporary) !== -1),
        new Option(Tag.DamageDown.toString(10), convertTagToString(Tag.DamageDown), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DamageDown) !== -1),
        new Option(Tag.SpeedDown.toString(10), convertTagToString(Tag.SpeedDown), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.SpeedDown) !== -1),
        new Option(Tag.ShotSpeedDown.toString(10), convertTagToString(Tag.ShotSpeedDown), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ShotSpeedDown) !== -1),
        new Option(Tag.TearsDown.toString(10), convertTagToString(Tag.TearsDown), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.TearsDown) !== -1),
        new Option(Tag.HealthDown.toString(10), convertTagToString(Tag.HealthDown), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.HealthDown) !== -1),
        new Option(Tag.RangeDown.toString(10), convertTagToString(Tag.RangeDown), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.RangeDown) !== -1),
        new Option(Tag.LuckDown.toString(10), convertTagToString(Tag.LuckDown), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.LuckDown) !== -1),
        new Option(Tag.RandomizesStats.toString(10), convertTagToString(Tag.RandomizesStats), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.RandomizesStats) !== -1),
        new Option(Tag.DamageMultiplier.toString(10), convertTagToString(Tag.DamageMultiplier), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DamageMultiplier) !== -1),
        new Option(Tag.CanRerollItemPedestals.toString(10), convertTagToString(Tag.CanRerollItemPedestals), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.CanRerollItemPedestals) !== -1),
        new Option(Tag.CanRerollPickups.toString(10), convertTagToString(Tag.CanRerollPickups), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.CanRerollPickups) !== -1),
        new Option(Tag.CanRerollCharacter.toString(10), convertTagToString(Tag.CanRerollCharacter), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.CanRerollCharacter) !== -1),
        new Option(Tag.CanRerollRocks.toString(10), convertTagToString(Tag.CanRerollRocks), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.CanRerollRocks) !== -1),
        new Option(Tag.CanRerollStats.toString(10), convertTagToString(Tag.CanRerollStats), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.CanRerollStats) !== -1),
        new Option(Tag.CanRerollFloor.toString(10), convertTagToString(Tag.CanRerollFloor), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.CanRerollFloor) !== -1),
        new Option(Tag.CanRerollEnemies.toString(10), convertTagToString(Tag.CanRerollEnemies), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.CanRerollEnemies) !== -1),
        new Option(Tag.CanRerollRoom.toString(10), convertTagToString(Tag.CanRerollRoom), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.CanRerollRoom) !== -1),
        new Option(Tag.Aura.toString(10), convertTagToString(Tag.Aura), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.Aura) !== -1),
        new Option(Tag.RemovesCurse.toString(10), convertTagToString(Tag.RemovesCurse), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.RemovesCurse) !== -1),
        new Option(Tag.AddsCurse.toString(10), convertTagToString(Tag.AddsCurse), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AddsCurse) !== -1),
        new Option(Tag.SpawnsFamiliarOrOrbital.toString(10), convertTagToString(Tag.SpawnsFamiliarOrOrbital), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.SpawnsFamiliarOrOrbital) !== -1),
        new Option(Tag.SpikeImmunity.toString(10), convertTagToString(Tag.SpikeImmunity), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.SpikeImmunity) !== -1),
        new Option(Tag.RandomStatusEffect.toString(10), convertTagToString(Tag.RandomStatusEffect), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.RandomStatusEffect) !== -1),
        new Option(Tag.ChangesChestBehavior.toString(10), convertTagToString(Tag.ChangesChestBehavior), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ChangesChestBehavior) !== -1),
        new Option(Tag.HasRandomEffect.toString(10), convertTagToString(Tag.HasRandomEffect), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.HasRandomEffect) !== -1),
        new Option(Tag.CrushesRocks.toString(10), convertTagToString(Tag.CrushesRocks), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.CrushesRocks) !== -1),
        new Option(Tag.IsSpacebarItem.toString(10), convertTagToString(Tag.IsSpacebarItem), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.IsSpacebarItem) !== -1),
        new Option(Tag.IsPassiveItem.toString(10), convertTagToString(Tag.IsPassiveItem), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.IsPassiveItem) !== -1),
        new Option(Tag.IsFamiliar.toString(10), convertTagToString(Tag.IsFamiliar), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.IsFamiliar) !== -1),
        new Option(Tag.DoubleTroubleBossfight.toString(10), convertTagToString(Tag.DoubleTroubleBossfight), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.DoubleTroubleBossfight) !== -1),
        new Option(Tag.NormalBossfight.toString(10), convertTagToString(Tag.NormalBossfight), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.NormalBossfight) !== -1),
        new Option(Tag.GoodPill.toString(10), convertTagToString(Tag.GoodPill), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.GoodPill) !== -1),
        new Option(Tag.BadPill.toString(10), convertTagToString(Tag.BadPill), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.BadPill) !== -1),
        new Option(Tag.ThreeStepsToTransformation.toString(10), convertTagToString(Tag.ThreeStepsToTransformation), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ThreeStepsToTransformation) !== -1),
        new Option(Tag.TwoStepsToTransform.toString(10), convertTagToString(Tag.TwoStepsToTransform), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.TwoStepsToTransform) !== -1),
        new Option(Tag.AbsorbsOtherItems.toString(10), convertTagToString(Tag.AbsorbsOtherItems), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AbsorbsOtherItems) !== -1),
        new Option(Tag.AppearsOnBasementOne.toString(10), convertTagToString(Tag.AppearsOnBasementOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnBasementOne) !== -1),
        new Option(Tag.AppearsOnBasementTwo.toString(10), convertTagToString(Tag.AppearsOnBasementTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnBasementTwo) !== -1),
        new Option(Tag.AppearsOnBasementXl.toString(10), convertTagToString(Tag.AppearsOnBasementXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnBasementXl) !== -1),
        new Option(Tag.AppearsOnCellarOne.toString(10), convertTagToString(Tag.AppearsOnCellarOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnCellarOne) !== -1),
        new Option(Tag.AppearsOnCellarTwo.toString(10), convertTagToString(Tag.AppearsOnCellarTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnCellarTwo) !== -1),
        new Option(Tag.AppearsOnCellarXl.toString(10), convertTagToString(Tag.AppearsOnCellarXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnCellarXl) !== -1),
        new Option(Tag.AppearsOnBurningBasementOne.toString(10), convertTagToString(Tag.AppearsOnBurningBasementOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnBurningBasementOne) !== -1),
        new Option(Tag.AppearsOnBurningBasementTwo.toString(10), convertTagToString(Tag.AppearsOnBurningBasementTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnBurningBasementTwo) !== -1),
        new Option(Tag.AppearsOnBurningBasementXl.toString(10), convertTagToString(Tag.AppearsOnBurningBasementXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnBurningBasementXl) !== -1),
        new Option(Tag.AppearsOnBlueWomb.toString(10), convertTagToString(Tag.AppearsOnBlueWomb), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnBlueWomb) !== -1),
        new Option(Tag.AppearsOnCatacombsOne.toString(10), convertTagToString(Tag.AppearsOnCatacombsOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnCatacombsOne) !== -1),
        new Option(Tag.AppearsOnCatacombsTwo.toString(10), convertTagToString(Tag.AppearsOnCatacombsTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnCatacombsTwo) !== -1),
        new Option(Tag.AppearsOnCatacombsXl.toString(10), convertTagToString(Tag.AppearsOnCatacombsXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnCatacombsXl) !== -1),
        new Option(Tag.AppearsOnCathedral.toString(10), convertTagToString(Tag.AppearsOnCathedral), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnCathedral) !== -1),
        new Option(Tag.AppearsOnCavesOne.toString(10), convertTagToString(Tag.AppearsOnCavesOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnCavesOne) !== -1),
        new Option(Tag.AppearsOnCavesTwo.toString(10), convertTagToString(Tag.AppearsOnCavesTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnCavesTwo) !== -1),
        new Option(Tag.AppearsOnCavesXl.toString(10), convertTagToString(Tag.AppearsOnCavesXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnCavesXl) !== -1),
        new Option(Tag.AppearsOnChest.toString(10), convertTagToString(Tag.AppearsOnChest), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnChest) !== -1),
        new Option(Tag.AppearsOnCorpseOne.toString(10), convertTagToString(Tag.AppearsOnCorpseOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnCorpseOne) !== -1),
        new Option(Tag.AppearsOnCorpseTwo.toString(10), convertTagToString(Tag.AppearsOnCorpseTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnCorpseTwo) !== -1),
        new Option(Tag.AppearsOnCorpseXl.toString(10), convertTagToString(Tag.AppearsOnCorpseXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnCorpseXl) !== -1),
        new Option(Tag.AppearsOnDankDepthsOne.toString(10), convertTagToString(Tag.AppearsOnDankDepthsOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnDankDepthsOne) !== -1),
        new Option(Tag.AppearsOnDankDepthsTwo.toString(10), convertTagToString(Tag.AppearsOnDankDepthsTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnDankDepthsTwo) !== -1),
        new Option(Tag.AppearsOnDankDepthsXl.toString(10), convertTagToString(Tag.AppearsOnDankDepthsXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnDankDepthsXl) !== -1),
        new Option(Tag.AppearsOnDarkRoom.toString(10), convertTagToString(Tag.AppearsOnDarkRoom), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnDarkRoom) !== -1),
        new Option(Tag.AppearsOnDepthsOne.toString(10), convertTagToString(Tag.AppearsOnDepthsOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnDepthsOne) !== -1),
        new Option(Tag.AppearsOnDepthsTwo.toString(10), convertTagToString(Tag.AppearsOnDepthsTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnDepthsTwo) !== -1),
        new Option(Tag.AppearsOnDepthsXl.toString(10), convertTagToString(Tag.AppearsOnDepthsXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnDepthsXl) !== -1),
        new Option(Tag.AppearsOnDownpourOne.toString(10), convertTagToString(Tag.AppearsOnDownpourOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnDownpourOne) !== -1),
        new Option(Tag.AppearsOnDownpourTwo.toString(10), convertTagToString(Tag.AppearsOnDownpourTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnDownpourTwo) !== -1),
        new Option(Tag.AppearsOnDownpourXl.toString(10), convertTagToString(Tag.AppearsOnDownpourXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnDownpourXl) !== -1),
        new Option(Tag.AppearsOnFloodedCavesOne.toString(10), convertTagToString(Tag.AppearsOnFloodedCavesOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnFloodedCavesOne) !== -1),
        new Option(Tag.AppearsOnFloodedCavesTwo.toString(10), convertTagToString(Tag.AppearsOnFloodedCavesTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnFloodedCavesTwo) !== -1),
        new Option(Tag.AppearsOnFloodedCavesXl.toString(10), convertTagToString(Tag.AppearsOnFloodedCavesXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnFloodedCavesXl) !== -1),
        new Option(Tag.AppearsOnGreedModeBasement.toString(10), convertTagToString(Tag.AppearsOnGreedModeBasement), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnGreedModeBasement) !== -1),
        new Option(Tag.AppearsOnGreedModeCaves.toString(10), convertTagToString(Tag.AppearsOnGreedModeCaves), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnGreedModeCaves) !== -1),
        new Option(Tag.AppearsOnGreedModeDepths.toString(10), convertTagToString(Tag.AppearsOnGreedModeDepths), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnGreedModeDepths) !== -1),
        new Option(Tag.AppearsOnGreedModeSheol.toString(10), convertTagToString(Tag.AppearsOnGreedModeSheol), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnGreedModeSheol) !== -1),
        new Option(Tag.AppearsOnGreedModeTheShop.toString(10), convertTagToString(Tag.AppearsOnGreedModeTheShop), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnGreedModeTheShop) !== -1),
        new Option(Tag.AppearsOnGreedModeUltraGreed.toString(10), convertTagToString(Tag.AppearsOnGreedModeUltraGreed), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnGreedModeUltraGreed) !== -1),
        new Option(Tag.AppearsOnGreedModeWomb.toString(10), convertTagToString(Tag.AppearsOnGreedModeWomb), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnGreedModeWomb) !== -1),
        new Option(Tag.AppearsOnMausoleumOne.toString(10), convertTagToString(Tag.AppearsOnMausoleumOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnMausoleumOne) !== -1),
        new Option(Tag.AppearsOnMausoleumTwo.toString(10), convertTagToString(Tag.AppearsOnMausoleumTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnMausoleumTwo) !== -1),
        new Option(Tag.AppearsOnMausoleumXl.toString(10), convertTagToString(Tag.AppearsOnMausoleumXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnMausoleumXl) !== -1),
        new Option(Tag.AppearsOnMinesOne.toString(10), convertTagToString(Tag.AppearsOnMinesOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnMinesOne) !== -1),
        new Option(Tag.AppearsOnMinesTwo.toString(10), convertTagToString(Tag.AppearsOnMinesTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnMinesTwo) !== -1),
        new Option(Tag.AppearsOnMinesXl.toString(10), convertTagToString(Tag.AppearsOnMinesXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnMinesXl) !== -1),
        new Option(Tag.AppearsOnNecropolisOne.toString(10), convertTagToString(Tag.AppearsOnNecropolisOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnNecropolisOne) !== -1),
        new Option(Tag.AppearsOnNecropolisTwo.toString(10), convertTagToString(Tag.AppearsOnNecropolisTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnNecropolisTwo) !== -1),
        new Option(Tag.AppearsOnNecropolisXl.toString(10), convertTagToString(Tag.AppearsOnNecropolisXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnNecropolisXl) !== -1),
        new Option(Tag.AppearsOnScarredWombOne.toString(10), convertTagToString(Tag.AppearsOnScarredWombOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnScarredWombOne) !== -1),
        new Option(Tag.AppearsOnScarredWombTwo.toString(10), convertTagToString(Tag.AppearsOnScarredWombTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnScarredWombTwo) !== -1),
        new Option(Tag.AppearsOnScarredWombXl.toString(10), convertTagToString(Tag.AppearsOnScarredWombXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnScarredWombXl) !== -1),
        new Option(Tag.AppearsOnSheol.toString(10), convertTagToString(Tag.AppearsOnSheol), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnSheol) !== -1),
        new Option(Tag.AppearsOnTheVoid.toString(10), convertTagToString(Tag.AppearsOnTheVoid), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnTheVoid) !== -1),
        new Option(Tag.AppearsOnUteroOne.toString(10), convertTagToString(Tag.AppearsOnUteroOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnUteroOne) !== -1),
        new Option(Tag.AppearsOnUteroTwo.toString(10), convertTagToString(Tag.AppearsOnUteroTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnUteroTwo) !== -1),
        new Option(Tag.AppearsOnUteroXl.toString(10), convertTagToString(Tag.AppearsOnUteroXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnUteroXl) !== -1),
        new Option(Tag.AppearsOnWombOne.toString(10), convertTagToString(Tag.AppearsOnWombOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnWombOne) !== -1),
        new Option(Tag.AppearsOnWombTwo.toString(10), convertTagToString(Tag.AppearsOnWombTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnWombTwo) !== -1),
        new Option(Tag.AppearsOnWombXl.toString(10), convertTagToString(Tag.AppearsOnWombXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.AppearsOnWombXl) !== -1),
        new Option(Tag.ComesAfterBasementOne.toString(10), convertTagToString(Tag.ComesAfterBasementOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterBasementOne) !== -1),
        new Option(Tag.ComesAfterBasementTwo.toString(10), convertTagToString(Tag.ComesAfterBasementTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterBasementTwo) !== -1),
        new Option(Tag.ComesAfterBasementXl.toString(10), convertTagToString(Tag.ComesAfterBasementXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterBasementXl) !== -1),
        new Option(Tag.ComesAfterCellarOne.toString(10), convertTagToString(Tag.ComesAfterCellarOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterCellarOne) !== -1),
        new Option(Tag.ComesAfterCellarTwo.toString(10), convertTagToString(Tag.ComesAfterCellarTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterCellarTwo) !== -1),
        new Option(Tag.ComesAfterCellarXl.toString(10), convertTagToString(Tag.ComesAfterCellarXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterCellarXl) !== -1),
        new Option(Tag.ComesAfterBurningBasementOne.toString(10), convertTagToString(Tag.ComesAfterBurningBasementOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterBurningBasementOne) !== -1),
        new Option(Tag.ComesAfterBurningBasementTwo.toString(10), convertTagToString(Tag.ComesAfterBurningBasementTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterBurningBasementTwo) !== -1),
        new Option(Tag.ComesAfterBurningBasementXl.toString(10), convertTagToString(Tag.ComesAfterBurningBasementXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterBurningBasementXl) !== -1),
        new Option(Tag.ComesAfterBlueWomb.toString(10), convertTagToString(Tag.ComesAfterBlueWomb), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterBlueWomb) !== -1),
        new Option(Tag.ComesAfterCatacombsOne.toString(10), convertTagToString(Tag.ComesAfterCatacombsOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterCatacombsOne) !== -1),
        new Option(Tag.ComesAfterCatacombsTwo.toString(10), convertTagToString(Tag.ComesAfterCatacombsTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterCatacombsTwo) !== -1),
        new Option(Tag.ComesAfterCatacombsXl.toString(10), convertTagToString(Tag.ComesAfterCatacombsXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterCatacombsXl) !== -1),
        new Option(Tag.ComesAfterCathedral.toString(10), convertTagToString(Tag.ComesAfterCathedral), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterCathedral) !== -1),
        new Option(Tag.ComesAfterCavesOne.toString(10), convertTagToString(Tag.ComesAfterCavesOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterCavesOne) !== -1),
        new Option(Tag.ComesAfterCavesTwo.toString(10), convertTagToString(Tag.ComesAfterCavesTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterCavesTwo) !== -1),
        new Option(Tag.ComesAfterCavesXl.toString(10), convertTagToString(Tag.ComesAfterCavesXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterCavesXl) !== -1),
        new Option(Tag.ComesAfterChest.toString(10), convertTagToString(Tag.ComesAfterChest), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterChest) !== -1),
        new Option(Tag.ComesAfterCorpseOne.toString(10), convertTagToString(Tag.ComesAfterCorpseOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterCorpseOne) !== -1),
        new Option(Tag.ComesAfterCorpseTwo.toString(10), convertTagToString(Tag.ComesAfterCorpseTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterCorpseTwo) !== -1),
        new Option(Tag.ComesAfterCorpseXl.toString(10), convertTagToString(Tag.ComesAfterCorpseXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterCorpseXl) !== -1),
        new Option(Tag.ComesAfterDankDepthsOne.toString(10), convertTagToString(Tag.ComesAfterDankDepthsOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterDankDepthsOne) !== -1),
        new Option(Tag.ComesAfterDankDepthsTwo.toString(10), convertTagToString(Tag.ComesAfterDankDepthsTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterDankDepthsTwo) !== -1),
        new Option(Tag.ComesAfterDankDepthsXl.toString(10), convertTagToString(Tag.ComesAfterDankDepthsXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterDankDepthsXl) !== -1),
        new Option(Tag.ComesAfterDarkRoom.toString(10), convertTagToString(Tag.ComesAfterDarkRoom), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterDarkRoom) !== -1),
        new Option(Tag.ComesAfterDepthsOne.toString(10), convertTagToString(Tag.ComesAfterDepthsOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterDepthsOne) !== -1),
        new Option(Tag.ComesAfterDepthsTwo.toString(10), convertTagToString(Tag.ComesAfterDepthsTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterDepthsTwo) !== -1),
        new Option(Tag.ComesAfterDepthsXl.toString(10), convertTagToString(Tag.ComesAfterDepthsXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterDepthsXl) !== -1),
        new Option(Tag.ComesAfterDownpourOne.toString(10), convertTagToString(Tag.ComesAfterDownpourOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterDownpourOne) !== -1),
        new Option(Tag.ComesAfterDownpourTwo.toString(10), convertTagToString(Tag.ComesAfterDownpourTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterDownpourTwo) !== -1),
        new Option(Tag.ComesAfterDownpourXl.toString(10), convertTagToString(Tag.ComesAfterDownpourXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterDownpourXl) !== -1),
        new Option(Tag.ComesAfterFloodedCavesOne.toString(10), convertTagToString(Tag.ComesAfterFloodedCavesOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterFloodedCavesOne) !== -1),
        new Option(Tag.ComesAfterFloodedCavesTwo.toString(10), convertTagToString(Tag.ComesAfterFloodedCavesTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterFloodedCavesTwo) !== -1),
        new Option(Tag.ComesAfterFloodedCavesXl.toString(10), convertTagToString(Tag.ComesAfterFloodedCavesXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterFloodedCavesXl) !== -1),
        new Option(Tag.ComesAfterGreedModeBasement.toString(10), convertTagToString(Tag.ComesAfterGreedModeBasement), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterGreedModeBasement) !== -1),
        new Option(Tag.ComesAfterGreedModeCaves.toString(10), convertTagToString(Tag.ComesAfterGreedModeCaves), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterGreedModeCaves) !== -1),
        new Option(Tag.ComesAfterGreedModeDepths.toString(10), convertTagToString(Tag.ComesAfterGreedModeDepths), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterGreedModeDepths) !== -1),
        new Option(Tag.ComesAfterGreedModeSheol.toString(10), convertTagToString(Tag.ComesAfterGreedModeSheol), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterGreedModeSheol) !== -1),
        new Option(Tag.ComesAfterGreedModeTheShop.toString(10), convertTagToString(Tag.ComesAfterGreedModeTheShop), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterGreedModeTheShop) !== -1),
        new Option(Tag.ComesAfterGreedModeUltraGreed.toString(10), convertTagToString(Tag.ComesAfterGreedModeUltraGreed), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterGreedModeUltraGreed) !== -1),
        new Option(Tag.ComesAfterGreedModeWomb.toString(10), convertTagToString(Tag.ComesAfterGreedModeWomb), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterGreedModeWomb) !== -1),
        new Option(Tag.ComesAfterMausoleumOne.toString(10), convertTagToString(Tag.ComesAfterMausoleumOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterMausoleumOne) !== -1),
        new Option(Tag.ComesAfterMausoleumTwo.toString(10), convertTagToString(Tag.ComesAfterMausoleumTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterMausoleumTwo) !== -1),
        new Option(Tag.ComesAfterMausoleumXl.toString(10), convertTagToString(Tag.ComesAfterMausoleumXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterMausoleumXl) !== -1),
        new Option(Tag.ComesAfterMinesOne.toString(10), convertTagToString(Tag.ComesAfterMinesOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterMinesOne) !== -1),
        new Option(Tag.ComesAfterMinesTwo.toString(10), convertTagToString(Tag.ComesAfterMinesTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterMinesTwo) !== -1),
        new Option(Tag.ComesAfterMinesXl.toString(10), convertTagToString(Tag.ComesAfterMinesXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterMinesXl) !== -1),
        new Option(Tag.ComesAfterNecropolisOne.toString(10), convertTagToString(Tag.ComesAfterNecropolisOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterNecropolisOne) !== -1),
        new Option(Tag.ComesAfterNecropolisTwo.toString(10), convertTagToString(Tag.ComesAfterNecropolisTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterNecropolisTwo) !== -1),
        new Option(Tag.ComesAfterNecropolisXl.toString(10), convertTagToString(Tag.ComesAfterNecropolisXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterNecropolisXl) !== -1),
        new Option(Tag.ComesAfterScarredWombOne.toString(10), convertTagToString(Tag.ComesAfterScarredWombOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterScarredWombOne) !== -1),
        new Option(Tag.ComesAfterScarredWombTwo.toString(10), convertTagToString(Tag.ComesAfterScarredWombTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterScarredWombTwo) !== -1),
        new Option(Tag.ComesAfterScarredWombXl.toString(10), convertTagToString(Tag.ComesAfterScarredWombXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterScarredWombXl) !== -1),
        new Option(Tag.ComesAfterSheol.toString(10), convertTagToString(Tag.ComesAfterSheol), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterSheol) !== -1),
        new Option(Tag.ComesAfterTheVoid.toString(10), convertTagToString(Tag.ComesAfterTheVoid), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterTheVoid) !== -1),
        new Option(Tag.ComesAfterUteroOne.toString(10), convertTagToString(Tag.ComesAfterUteroOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterUteroOne) !== -1),
        new Option(Tag.ComesAfterUteroTwo.toString(10), convertTagToString(Tag.ComesAfterUteroTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterUteroTwo) !== -1),
        new Option(Tag.ComesAfterUteroXl.toString(10), convertTagToString(Tag.ComesAfterUteroXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterUteroXl) !== -1),
        new Option(Tag.ComesAfterWombOne.toString(10), convertTagToString(Tag.ComesAfterWombOne), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterWombOne) !== -1),
        new Option(Tag.ComesAfterWombTwo.toString(10), convertTagToString(Tag.ComesAfterWombTwo), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterWombTwo) !== -1),
        new Option(Tag.ComesAfterWombXl.toString(10), convertTagToString(Tag.ComesAfterWombXl), selectedTags && selectedTags.length > 0 && selectedTags.indexOf(Tag.ComesAfterWombXl) !== -1),
    ];
}

export {
    existsInOptionlist,
    gameModeOptionList,
    resourceTypeOptionList,
    tagsOptionList
}

