export enum GameplayEventType {
    Unspecified = 0,
    CharacterDied,
    ItemCollected,
    DownToTheNextFloor,
    Bossfight,
    Pill,
    TarotCard,
    Rune,
    Trinket,
    Curse,
    OtherConsumable,
    TransformationComplete,
    TransformationProgress,
    LastFloor,
    AbsorbedItem,
    CharacterReroll,
    WonTheRun,
    LostTheRun,
    ItemTouched,
    StartingTrinket
}